name: Primeiro pipeline

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verificar formatação de código
        run: npm run format:check

      - name: Run linter
        run: npm run lint

      - name: Detectar código duplicado
        run: npm run cpd

      - name: Build project
        run: npm run build

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Generate UML Diagram
        run: npm run uml:generate

      - name: Upload UML Diagram
        uses: actions/upload-artifact@v6
        with:
          name: class-diagram
          path: uml.png